<?php
// Set doctype explicitly if it is not `HTML4_LOOSE`, i.e. 'HTML 4.01 Transitional'
$this->doctype('HTML5');

// Load translation data
$this->i18nTheme();

// Get module name
$module = Pi::service('module')->current();

//HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
$this->js(array(
    pi::url('static/js/html5shiv.js') => array(
        'conditional' => 'lt IE 9'
    ),
    pi::url('static/js/respond.min.js') => array(
        'conditional' => 'lt IE 9'
    ),
));

// Load jQuery
if ($module == 'system') {
    $this->jQuery(array(
        'extension/owl.carousel.min.js',
        'extension/owl.carousel.css',
    ));
} else {
    $this->jquery();
}

// Load Bootstrap css/js and font-awesome
$this->bootstrap(array(
    'js/bootstrap.min.js',
    'font-awesome/css/font-awesome.min.css'
));

// Load front.css
$this->css($this->assetTheme('css/front.css'));

// Load localization css
$this->css($this->assetLocale('locale.css'));

// Load front.js on footer
$this->footScript()->appendFile($this->assetTheme('js/front.js'));

// Apple icons
// Apple icon for iphone
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'href'  => $this->assetTheme('image/touch-icon-iphone.png')
));
// Apple icon for ipad
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '72x72',
    'href'  => $this->assetTheme('image/touch-icon-ipad.png')
));
// Apple icon for iphone retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-iphone-retina.png')
));
// Apple icon for ipad retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-ipad-retina.png')
));

// Meta Viewport Tag
$this->headMeta('width=device-width, initial-scale=1.0', 'viewport');

// Explicitly load favicon
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/x-icon',
    'href'  => $this->favicon(),
));
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/png',
    'href'  => $this->favicon('favicon.png'),
));

// Load google analytics code
$this->ga();

// Get navigation
$navigation = $this->nav('front');

// Get block
$blocks = $this->blocks();
$blockTemplate = $this->template('block');

// Get breadcrumbs
$breadcrumbs = $this->breadcrumb(
    array('prefix' => array(
        array(
            'label' => __('Home'),
            'href' => Pi::url($this->url('home'))
        )
    ))
);

// Show / Hide block
$script = "
(function($) {
    // Shwo hide form
    $(document).ready(function(){
        hidden = true;
        $('#show-submit').click(function(){
            if(hidden == false) {
                $('#order-more-info').slideUp('slow');
                $('#hide-submit').attr('id', 'show-submit').html('آخرین وضعیت مانده اقساط');
                hidden = true;
            } else {
                $('#order-more-info').slideDown('slow'); 
                $('#show-submit').attr('id', 'hide-submit').html('بستن پنجره');
                hidden = false;
            }
        });
    });
})(jQuery)
";
$this->footScript()->appendScript($script);
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
</head>
<body id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?>">
<header class="pi-header">
    <div class="container">
        <div class="row clearfix">
            <?php // if (Pi::user()->getId() > 0) { ?>
            <div class="col-md-5">
                <div class="pi-header-logo">
                    <?php if ($module == 'system') { ?>
                        <h1>
                            <a title="<?php echo _escape($sitename); ?>" href="<?php echo Pi::url($this->url('home')); ?>">
                                <img src="<?php echo $this->logo(); ?>" alt="<?php echo _escape($sitename); ?>">
                            </a>
                        </h1>
                    <?php } else { ?>
                        <h2>
                            <a title="<?php echo _escape($sitename); ?>" href="<?php echo Pi::url($this->url('home')); ?>">
                                <img src="<?php echo $this->logo(); ?>" alt="<?php echo _escape($sitename); ?>">
                            </a>
                        </h2>
                    <?php } ?>
                </div>
            </div>
            <div class="col-md-7 text-right">
                <div class="clearfix">
                    <?php echo $this->widget('system-user-bar'); ?>
                </div>
                <div class="clearfix">
                    <?php echo $this->widget('search-search'); ?>
                </div>
            </div>
            <div class="col-md-12">
                <div class="navbar navbar-inverse yamm">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <i class="fa fa-bars"></i>
                        </button>
                    </div>
                    <div id="navbar-collapse-grid" class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li><a title="خانه" href="<?php echo Pi::url($this->url('home')); ?>"><i class="fa fa-home"></i></a></li>
                            <li class="dropdown yamm-fw">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle">کالای دیجیتال<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li class="grid-demo">
                                        <div class="row">
                                            <div class="col-sm-3">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/mobile">موبایل</a></h4>
                                                <ul class="list-unstyled col-sm-6">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/APPLE">APPLE</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/ASUS">ASUS</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/HTC">HTC</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/HUAWEI">HUAWEI</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/LG">LG</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/MOTOROLA">MOTOROLA</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/NOKIA">NOKIA</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/SAMSUNG">SAMSUNG</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/SONY">SONY</a></li>
                                                </ul>
                                                <ul class="list-unstyled col-sm-6">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/android-mobile">ANDROID</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/ios-mobile">IOS</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/windows-mobile">WIDOWS</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-sm-2">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/laptop">لپ تاپ</a></h4>
                                                <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/acer-laptop">ACER</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/apple-laptop">APPLE</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/asus-laptop">ASUS</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/dell-laptop">DELL</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/hp-laptop">HP</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/lenovo-laptop">LENOVO</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/msi-laptop">MSI</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/sony-laptop">SONY</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-sm-3">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/tablet">تبلت</a></h4>
                                                <ul class="list-unstyled col-sm-6">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/acer-tablet">ACER</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/appletablet">APPLE</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/ainol-tablet">AINOL</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/asus-tablet">ASUS</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/lenovo-tablet">LENOVO</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/huawei-tablet">HUAWEI</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/microsaft-tablet">MICROSAFT</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/samsung-tablet">SAMSUNG</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/sony-tablet">SONY</a></li>
                                                </ul>
                                                <div class="col-sm-6">
                                                    <ul class="list-unstyled">
                                                        <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/android-tablet">ANDROID</a></li>
                                                        <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/ios-tablet">IOS</a></li>
                                                        <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/windows-tablet">Windows</a></li>
                                                    </ul>
                                                    <ul class="list-unstyled">
                                                        <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/کمتر-از-9-اینچ">کمتر از 9 اینچ</a></li>
                                                        <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/بین-9-تا-11-اینچ">بین 9 تا 11 اینچ</a></li>
                                                        <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/bozorg-tar-az-11-inch">بزرگتر از 11 اینچ</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="col-sm-2">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/دوربین">دوربین</a></h4>
                                                <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/DSLR">DSLR</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/کامپکت-ساده">کامپکت ساده</a></li>
                                                </ul>
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/کتاب-خوان">کتاب‌خوان</a></h4>
                                                <!-- <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/E-INK">E-INK</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/LCD">LCD</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/E-INK-Vizplex">E-INK Vizplex</a></li>
                                                 </ul> -->
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <li class="dropdown yamm-fw">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle">لوازم برقی<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li class="grid-demo">
                                        <div class="row">
                                            <div class="col-sm-4">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/تلویزیون">تلویزیون</a></h4>
                                                <ul class="list-unstyled col-sm-6">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/کوچیکتر-از-32-اینچ">کوچکتر از 32 اینچ</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/32-تا-39-اینچ">از 32 تا 39 اینچ</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/40-تا-48-اینچ">از 40 تا 48 اینچ</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/50-تا-55-اینچ">از 50 تا 55 اینچ</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/60-اینچ-و-بزرگتر">بزرگتر از 60 اینچ</a></li>
                                                </ul>
                                                <ul class="list-unstyled col-sm-6">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/sony-tv">SONY</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/samsung-tv">SAMSUNG</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/LG-tv">LG</a></li>
                                                    <!-- <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/sharp-tv">SHARP</a></li> -->
                                                </ul>
                                            </div>
                                            <div class="col-sm-2">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/کنسول-بازی">کنسول بازی</a></h4>
                                                <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/کنسول-خانگی">کنسول خانگی</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/کنسول-قابل-حمل">کنسول قابل حمل</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/لوازم-جانبی-کنسول-بازی">لوازم جانبی کنسول بازی</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-sm-2">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/سینمای-خانگی">سینمای خانگی</a></h4>
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/سیستم-صوتی-خانگی">سیستم صوتی خانگی</a></h4>
                                            </div>
                                            <div class="col-sm-2">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/بخش-کننده-چند-رسانه-ای-خانگی">پخش کننده چند رسانه ای خانگی</a></h4>
                                                <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/بخش-کننده-blue-rey">پخش کننده blu-rey</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/پخش-کننده-DVD">پخش کننده DVD</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/پخش-کننده-پرتابل">پخش کننده پرتابل</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/پخش-کننده-خانگی">پخش کننده خانگی</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-sm-2">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/سیستم-صوتی-و-تصویری-خودرو">سیستم صوتی و تصویری خودرو</a></h4>
                                                <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/دستگاه-پخش-خودرو">دستگاه پخش خودرو</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/امپلی-فایر-خودرو">امپلی فایر خودرو</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/ساب-ووفر">ساب ووفر</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <li class="dropdown yamm-fw">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle">لوازم خانگی<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li class="grid-demo">
                                        <div class="row">
                                            <div class="col-sm-2">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/لوازم-پخت-و-پز">لوازم پخت و پز</a></h4>
                                                <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/فر-و-ماکروویو">فر و ماکروویو</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/سرخ-کن">سرخ کن</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/توستر">توستر</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/آون-توستر">آون توستر</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/ساندویچ-ساز">ساندویچ ساز</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/پلوپز،آرامپز،بخار-و-زود-پز">پلوپز،آرامپز،بخار و زود پز</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-sm-2">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/نوشیدنی-ساز">نوشیدنی ساز</a></h4>
                                                <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/آبمیوه-گیری">آبمیوه گیری</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/چای-ساز">چای ساز</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/قهوه-ساز">قهوه ساز</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/اسپرسو-ساز">اسپرسو ساز</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/تصفیه-آب-و-آب-سرد-کن">تصفیه آب و آب سرد کن</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/کتری-برقی">کتری برقی</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-sm-2">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/خرد-کن-و-غذا-ساز">خرد کن و غذا ساز</a></h4>
                                                <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/غذا-ساز">غذا ساز</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/همزن">همزن</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/مخلوط-کن">مخلوط کن</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/چرخ-گوشت">چرخ گوشت</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/خرد-کن">خرد کن</a></li>
                                                </ul>
                                            </div>
                                            <!-- <div class="col-sm-2">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/لوازم-مکمل-آشپز-خانه">لوازم مکمل آشپز خانه</a></h4>
                                            </div> -->
                                            <div class="col-sm-2">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/لوازم-شست-شو-و-نظافت">لوازم شست شو و نظافت</a></h4>
                                                <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/جاروشارژی">جاروشارژی</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/اتو">اتو</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/بخارشو">بخارشو</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-sm-2">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/سرمایشی-و-گرمایشی">سرمایشی و گرمایشی</a></h4>
                                                <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/هیتر">هیتر</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/کولر">کولر</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/پنکه">پنکه</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/شوفاژ-برقی">شوفاژ برقی</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/تصفه-هوا">تصفه هوا</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <li class="dropdown yamm-fw">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle">لوازم شخصی<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li class="grid-demo">
                                        <div class="row">
                                            <div class="col-sm-3">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/سشوار">سشوار</a></h4>
                                                <!-- <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/PHILIPS">PHILIPS</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/PANASONIC">PANASONIC</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/BABYLISS">BABYLISS</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/REMINGTON">REMINGTON</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/BOSCH">BOSCH</a></li>
                                                </ul> -->
                                            </div>
                                            <div class="col-sm-3">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/اتو و حالت دهنده مو">اتو و حالت دهنده مو</a></h4>
                                                <!-- <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/PHILIPS-1">PHILIPS</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/PANASONIC-1">PANASONIC</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/BABYLISS-1">BABYLISS</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/REMINGTON-1">REMINGTON</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/BOSCH-1">BOSCH</a></li>
                                                </ul> -->
                                            </div>
                                            <!-- <div class="col-sm-2">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/بهداشت-و-زیبایی-ناخن">بهداشت و زیبایی ناخن</a></h4>
                                                <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/BABYLISS-2">BABYLISS</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/PANASONIC-2">PANASONIC</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/BEURER-2">BEURER</a></li>
                                                </ul>
                                            </div> -->
                                            <!-- <div class="col-sm-2">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/بیگودی-و-فر-کننده-مو">بیگودی و فر کننده مو</a></h4>
                                                <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/PHILIPS-3">PHILIPS</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/BABYLISS-3">BABYLISS</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/REMINGTON-3">REMINGTON</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/BOSCH-3">BOSCH</a></li>
                                                </ul>
                                            </div> -->
                                            <div class="col-sm-3">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/ماشین-ریش-تراش-و-اصلاح-موی-سر">ماشین ریش تراش و اصلاح موی سر</a></h4>
                                                <!-- <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/چرخشی-سه-تیغه">چرخشی(سه تیغه)</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/فویلی">فویلی</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/تریمر">تریمر</a></li>
                                                </ul> -->
                                            </div>
                                            <!-- <div class="col-sm-3">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/اصلاح-موی-سر">اصلاح موی سر</a></h4>
                                                <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/PANASONIC-4">PANASONIC</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/REMINGTON-4">REMINGTON</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/PHILIPS-4">PHILIPS</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/BABYLISS-4">BABYLISS</a></li>
                                                </ul>
                                            </div> -->
                                            <div class="col-sm-3">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/اصلاح-موی-بدن-بانوان">اصلاح موی بدن بانوان</a></h4>
                                                <!-- <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/اپیلاتور">اپیلاتور</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/لیزر">لیزر</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/4فویلی">فویلی</a></li>
                                                </ul> -->
                                            </div>
                                            <!-- <div class="col-sm-3">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/اصلاح-موی-بدن-آقایان">اصلاح موی بدن آقایان</a></h4>
                                                <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/PANASONIC-5">PANASONIC</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/REMINGTON-5">REMINGTON</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/PHILIPS-5">PHILIPS</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/BABYLISS-5">BABYLISS</a></li>
                                                </ul>
                                            </div> -->
                                            <div class="col-sm-3">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/فشار-سنج">فشار سنج</a></h4>
                                                <!-- <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/مچی">مچی</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/بازویی">بازویی</a></li>
                                                </ul> -->
                                            </div>
                                            <div class="col-sm-3">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/ترازو">ترازو</a></h4>
                                                <!-- <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/دیجیتال">دیجیتال</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/مکانیکی">مکانیکی</a></li>
                                                </ul> -->
                                            </div>
                                            <div class="col-sm-3">
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/ماساژور">ماساژور</a></h4>
                                                <!-- <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/دستی">دستی</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/برقی">برقی</a></li>
                                                </ul> -->
                                            </div>
                                            <div class="col-sm-3">
                                                <!-- <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/تشک-و-پتوی-برقی">تشک و پتوی برقی</a></h4> -->
                                                <h4><a href="<?php echo Pi::url($this->url('home')); ?>shop/مسواک-برقی">مسواک برقی</a></h4>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <li><a title="وبلاگ" href="<?php echo Pi::url($this->url('home')); ?>blog">وبلاگ</a></li>
                        </ul>
                        <?php if (Pi::user()->getId() > 0) { ?>
                            <span class="navbar-mainbtn pull-right">
                                <a class="btn btn-danger btn-sm" title="آخرین وضعیت مانده اقساط" id="show-submit">آخرین وضعیت مانده اقساط</a>
                            </span>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<section class="pi-main-container">
    <?php if (Pi::user()->getId() > 0) { ?>
        <div id="header-orderinfo">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div id="order-more-info">
                            <?php echo $this->widget('order-installment'); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
    <div class="container">
        <?php if ($breadcrumbs) { echo $breadcrumbs; } ?>
        <!-- Flash messenger -->
        <?php include $this->template('flash-messenger'); ?>
        <!-- Top head zone -->
        <?php if (!empty($blocks['0'])) { ?>
            <div class="pi-zone-0">
                <?php foreach ($blocks['0'] as $block) {
                    include $blockTemplate;
                } ?>
            </div>
        <?php } ?>
        <div class="row">
            <!-- Left zone -->
            <?php if (!empty($blocks['1'])) { ?>
                <div class="pi-zone-1 col-md-3">
                    <?php foreach ($blocks['1'] as $block) {
                        include $blockTemplate;
                    } ?>
                    <div class="panel panel-default ">
                        <div class="panel-heading">
                            <h2 class="panel-title">گواهینامه ها</h2>
                        </div>
                        <div class="panel-body">
                            <div class="clearfix text-center">
                                <ul class="list-inline row">
                                    <li class="col-md-4"><a target="_blank" href="http://www.emrouzkharid.com/crt.php" title="نماد اعتماد الکترونیک"><img alt="نماد اعتماد الکترونیک" class="img-responsive" src="<?php echo Pi::url($this->url('home')); ?>asset/theme-emrouzkharid/image/enamad.png" /></a></li>
                                    <li class="col-md-4"><img alt="بانک ملت" class="img-responsive" src="<?php echo Pi::url($this->url('home')); ?>asset/theme-emrouzkharid/image/behpardakht.png" /></li>
                                    <li class="col-md-4"><img alt="بانک پاسارگاد" class="img-responsive" src="<?php echo Pi::url($this->url('home')); ?>asset/theme-emrouzkharid/image/pasaragad.png" /></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            <?php } ?>
            <div class="<?php
            if (isset($blocks['1']) && isset($blocks['8'])) {
                echo 'col-md-6';
            } elseif (isset($blocks['1']) || isset($blocks['8'])) {
                echo 'col-md-9';
            } else {
                echo 'col-md-12';
            }
            ?>">
                <!-- Center top zone -->
                <?php if (isset($blocks['2'])) { ?>
                    <div class="pi-zone-2">
                        <?php foreach ($blocks['2'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
                <?php if (isset($blocks['3']) || isset($blocks['4'])) { ?>
                    <div class="row">
                        <div class="col-md-3 pi-zone-3">
                            <?php
                            if (isset($blocks['3'])) {
                                foreach ($blocks['3'] as $block) {
                                    include $blockTemplate;
                                }
                            }
                            ?>
                        </div>
                        <div class="col-md-9 pi-zone-4">
                            <?php
                            if (isset($blocks['4'])) {
                                foreach ($blocks['4'] as $block) {
                                    include $blockTemplate;
                                }
                            }
                            ?>
                        </div>
                    </div>
                <?php } ?>

                <!-- Module content starts -->
                <?php if (!empty($content)) { ?>
                    <div class="<?php echo $module; ?>">
                        <div class="pi-module-content" ng-app="<?php echo $module; ?>">
                            <?php echo $content; ?>
                        </div>
                        <?php echo Pi::service('comment')->load(array('options' => array('type' => 'js'))); ?>
                    </div>
                <?php } ?>
            </div>
            <!-- Right zone -->
            <?php if (isset($blocks['8'])) { ?>
                <div class="col-md-3 pi-zone-8">
                    <?php foreach ($blocks['8'] as $block) {
                        include $blockTemplate;
                    } ?>
                </div>
            <?php } ?>
        </div>
        <!-- Module content ends -->
        <?php if (isset($blocks['5']) || isset($blocks['6']) || isset($blocks['7'])) { ?>
            <div class="row pi-zone-bottom">
                <!-- Center bottom zone -->
                <?php if (isset($blocks['7'])) { ?>
                    <div class="col-md-12 pi-zone-7">
                        <?php foreach ($blocks['7'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
                <div class="col-md-6 pi-zone-5">
                    <?php
                    if (isset($blocks['5'])) {
                        foreach ($blocks['5'] as $block) {
                            include $blockTemplate;
                        }
                    }
                    ?>
                </div>
                <div class="col-md-6 pi-zone-6">
                    <?php
                    if (isset($blocks['6'])) {
                        foreach ($blocks['6'] as $block) {
                            include $blockTemplate;
                        }
                    }
                    ?>
                </div>
            </div>
        <?php } ?>
        <!-- Bottom foot zone -->
        <?php if (isset($blocks['99'])) { ?>
            <div class="pi-zone-99">
                <?php foreach ($blocks['99'] as $block) {
                    include $blockTemplate;
                } ?>
            </div>
        <?php } ?>
    </div>
</section>
<footer class="pi-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="pi-footer-title">
                    <h2>سایت امروز خرید‬</h2>
                </div>
                <div class="pi-footer-content">فروشگاه اینترنتی کالاهای دیجیتال و لوازم خانگی‬</div>
            </div>
            <div class="col-md-4 row">
                <ul class="list-unstyled col-md-6">
                    <li><a title="درباره ما" href="<?php echo Pi::url($this->url('home')); ?>page/about-us"><i class="fa fa-angle-left"></i> درباره ما</a></li>
                    <li><a title="تماس با ما" href="<?php echo Pi::url($this->url('home')); ?>contact"><i class="fa fa-angle-left"></i>تماس با ما</a></li>
                </ul>
                <ul class="list-unstyled col-md-6">
                    <li><a title="راهنمای خرید" href="<?php echo Pi::url($this->url('home')); ?>page/guide"><i class="fa fa-angle-left"></i>راهنمای خرید</a></li>
                    <li><a title="شرایط و مقررات" href="<?php echo Pi::url($this->url('home')); ?>page/terms"><i class="fa fa-angle-left"></i>شرایط و مقررات</a></li>
                </ul>
            </div>
            <div class="col-md-5">
                <ul class="list-unstyled">
                    <li>آدرس : تهران - انتهای اشرفی اصفهانی - حصارک - میدان توحید - پلاک 10 -طبقه 4</li>
                    <li>تلفن تماس : 1615054-0912 و 44836932-021</li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="pi-footer-copyright clearfix">
                <div class="text-left col-md-6">
                    <p>تمام حقوق برای وب سایت <a title="امروز خرید" href="<?php echo Pi::url($this->url('home')); ?>">امروز خرید</a> محفوظ است.</p>
                </div>
                <div class="text-right col-md-6">
                    <p><a title="طراحی و توسعه فراگسترش" href="http://www.faragostaresh.com">طراحی و توسعه فراگسترش</a></p>
                </div>
            </div>
        </div>
    </div>
</footer>
<div class="footer-order">
    <a href="<?php echo Pi::url($this->url('home')); ?>contact"><span>سفارش کالاهایی که در حال حاضر در سایت موجود نیستند</span></a>
</div>
</body>
</html>